# further cleaning of data files. Takes the files generated by 0_2_european_data_cleaning.R and does cosmetic changes.
# FB edited on 09/12/2022 to add Iceland
set.seed(1234)
source('code/Utils.R')
amr_summary <- read.csv(file = "data/original/summary_AMR.csv")

colnames(amr_summary)[colnames(amr_summary)=="DateUsedForStatisticsYear"] <- "Year"
amr_summary$patientType[amr_summary$patientType=="NULL"] <- "UNK"
amr_summary$patientType[amr_summary$patientType=="O"] <- "OUTPAT" #  Patients that go to the hospital for Dialysis, other Day Hospital Care and to Emergency room should be classified as O
colnames(amr_summary)[colnames(amr_summary)=="ReportingCountry"] <- "Country"
amr_summary <- amr_summary[!is.na(amr_summary$Pathogen),]

# renaming of Countries in long format
amr_summary$Country <- as.character(amr_summary$Country)
amr_summary$Country[amr_summary$Country=="AT"] <- "Austria"
amr_summary$Country[amr_summary$Country=="BE"] <- "Belgium"
amr_summary$Country[amr_summary$Country=="BG"] <- "Bulgaria"
amr_summary$Country[amr_summary$Country=="CY"] <- "Cyprus"
amr_summary$Country[amr_summary$Country=="CZ"] <- "Czech Republic"
amr_summary$Country[amr_summary$Country=="DE"] <- "Germany"
amr_summary$Country[amr_summary$Country=="DK"] <- "Denmark"
amr_summary$Country[amr_summary$Country=="EE"] <- "Estonia"
amr_summary$Country[amr_summary$Country=="EL"] <- "Greece"
amr_summary$Country[amr_summary$Country=="ES"] <- "Spain"
amr_summary$Country[amr_summary$Country=="FI"] <- "Finland"
amr_summary$Country[amr_summary$Country=="FR"] <- "France"
amr_summary$Country[amr_summary$Country=="HR"] <- "Croatia"
amr_summary$Country[amr_summary$Country=="HU"] <- "Hungary"
amr_summary$Country[amr_summary$Country=="IS"] <- "Iceland"
amr_summary$Country[amr_summary$Country=="IE"] <- "Ireland"
amr_summary$Country[amr_summary$Country=="IT"] <- "Italy"
amr_summary$Country[amr_summary$Country=="LT"] <- "Lithuania"
amr_summary$Country[amr_summary$Country=="LU"] <- "Luxembourg"
amr_summary$Country[amr_summary$Country=="LV"] <- "Latvia"
amr_summary$Country[amr_summary$Country=="MT"] <- "Malta"
amr_summary$Country[amr_summary$Country=="NL"] <- "Netherlands"
amr_summary$Country[amr_summary$Country=="NO"] <- "Norway"
amr_summary$Country[amr_summary$Country=="PL"] <- "Poland"
amr_summary$Country[amr_summary$Country=="PT"] <- "Portugal"
amr_summary$Country[amr_summary$Country=="RO"] <- "Romania"
amr_summary$Country[amr_summary$Country=="SE"] <- "Sweden"
amr_summary$Country[amr_summary$Country=="SI"] <- "Slovenia"
amr_summary$Country[amr_summary$Country=="SK"] <- "Slovakia"
amr_summary$Country[amr_summary$Country=="UK"] <- "United Kingdom"

# add antibiotic names and classes

#make better naming for the plots - matched via https://journals.asm.org/abbreviations-conventions and https://microbiologie-clinique.com/antibiotic-family-abbreviation.html
# ReportingProtocol.pdf is the place to look!
# FB checked this whole list 02/06/2023 and corrected three mistakes:
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="AMC"] <- "Amoxicillin + clavulanic acid"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="AMK"] <- "Amikacin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="AMP"] <- "Ampicillin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="AMX"] <- "Amoxicillin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="AZM"] <- "Azithromycin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="CAZ"] <- "Ceftazidime"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="CIP"] <- "Ciprofloxacin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="CLO"] <- "Cloxacillin" # FB corrected Clofazimine to Cloxacillin
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="CLR"] <- "Clarithromycin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="COL"] <- "Colistin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="CRO"] <- "Ceftriaxone"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="CTX"] <- "Cefotaxime"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="DAP"] <- "Daptomycin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="DIC"] <- "Dicloxacillin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="DOR"] <- "Doripenem"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="ERY"] <- "Erythromycin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="ETP"] <- "Ertapenem"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="FEP"] <- "Cefepime"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="FLC"] <- "Flucloxacillin" # FB corrected Fluconazole to Flucloxacillin
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="FOX"] <- "Cefoxitin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="GEH"] <- "Gentamicin High"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="GEN"] <- "Gentamicin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="IPM"] <- "Imipenem"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="LNZ"] <- "Linezolid"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="LVX"] <- "Levofloxacin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="MEM"] <- "Meropenem"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="MET"] <- "Meticillin" # FB corrected "Metronidazole" to Meticillin
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="MFX"] <- "Moxifloxacin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="NAL"] <- "Nalidixic acid"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="NET"] <- "Netilmicin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="NOR"] <- "Norfloxacin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="OFX"] <- "Ofloxacin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="OXA"] <- "Oxacillin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="PEN"] <- "Penicillin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="PIP"] <- "Piperacillin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="POL"] <- "Polymyxin B"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="RIF"] <- "Rifampicin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="TEC"] <- "Teicoplanin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="TGC"] <- "Tigecycline" # FB note the ReportingProtocol.pdf has  mistake, it writes 'TCG'
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="TOB"] <- "Tobramycin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="TZP"] <- "Piperacillin + Tazobactam"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="VAN"] <- "Vancomycin"
amr_summary$Antibiotic_long[amr_summary$Antibiotic=="MDR"] <- "Multidrug resistant" # FB added this

# matched via https://en.wikipedia.org/wiki/ATC_code_J01
# FB checked this whole list 02/06/2023 and corrected the three corresponding to the three mistakes above
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="AMC"] <- "J01C"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="AMK"] <- "J01G"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="AMP"] <- "J01C"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="AMX"] <- "J01C"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="AZM"] <- "J01F"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="CAZ"] <- "J01D"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="CIP"] <- "J01M"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="CLO"] <- "J01C" # FB corrected J04B to J01C
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="CLR"] <- "J01F"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="COL"] <- "J01X"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="CRO"] <- "J01D"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="CTX"] <- "J01D" 
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="DAP"] <- "J01X"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="DIC"] <- "J01C"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="DOR"] <- "J01D" 
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="ERY"] <- "J01F"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="ETP"] <- "J01D"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="FEP"] <- "J01D"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="FLC"] <- "J01C" # FB corrected J02A to J01C
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="FOX"] <- "J01D"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="GEN"] <- "J01G"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="GEH"] <- "J01G"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="IPM"] <- "J01D"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="LNZ"] <- "J01X"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="LVX"] <- "J01M"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="MEM"] <- "J01D"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="MET"] <- "J01C" # FB corrected J01X to J01C
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="MFX"] <- "J01M"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="NAL"] <- "J01M"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="NET"] <- "J01G"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="NOR"] <- "J01M"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="OFX"] <- "J01M"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="OXA"] <- "J01C"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="PEN"] <- "J01C"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="PIP"] <- "J01C"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="POL"] <- "J01X"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="RIF"] <- "J04A"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="TEC"] <- "J01X"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="TGC"] <- "J01A"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="TOB"] <- "J01G"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="TZP"] <- "J01C"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="VAN"] <- "J01X"
amr_summary$Antibiotic_class[amr_summary$Antibiotic=="MDR"] <- "MDR"

amr_summary$Pathogen_long[amr_summary$Pathogen=='STRPNE'] <- 'S. pneumoniae'
amr_summary$Pathogen_long[amr_summary$Pathogen=='STAAUR'] <- 'S. aureus'
amr_summary$Pathogen_long[amr_summary$Pathogen=='ENCFAE'] <- 'E. faecalis'
amr_summary$Pathogen_long[amr_summary$Pathogen=='ENCFAI'] <- 'E. faecium'
amr_summary$Pathogen_long[amr_summary$Pathogen=='ESCCOL'] <- 'E. coli'
amr_summary$Pathogen_long[amr_summary$Pathogen=='KLEPNE'] <- 'K. pneumoniae'
amr_summary$Pathogen_long[amr_summary$Pathogen=='PSEAER'] <- 'P. aeruginosa'
amr_summary$Pathogen_long[amr_summary$Pathogen=='ACISPP'] <- 'Acinetobaccter spp.'

amr_summary$combR <- paste(amr_summary$Pathogen, amr_summary$Country, amr_summary$Antibiotic, sep = "|")

# compare correlation of AMR inpat and outpat data
# filter out UNK datapoints
amr_summary_inpatoutpat <- amr_summary %>% filter(patientType %in% c('INPAT', 'OUTPAT'))
# make a new combination of Pathogen, Country, Antibiotic, Year to match INPAT and OUTPAT
amr_summary_inpatoutpat$combnew <- paste(amr_summary_inpatoutpat$Pathogen, amr_summary_inpatoutpat$Country, amr_summary_inpatoutpat$Antibiotic, amr_summary_inpatoutpat$Year, sep = "|")
# match them and only retain what has more than two elements per year, so both INPAT and OUTPAT
amr_summary_inpatoutpat <- amr_summary_inpatoutpat %>% group_by(combnew) %>% filter(n() == 2)
# small check - should have equally many datapoints
table(amr_summary_inpatoutpat$patientType)
# split by patientType
amr_summary_inpatoutpat_split <- amr_summary_inpatoutpat %>% group_by(combnew) %>% select (combnew, patientType, p) %>% split(amr_summary_inpatoutpat$patientType)
# complicated way to get two p that correspond to INPAT and OUTPAT
amr_summary_inpat <- amr_summary_inpatoutpat_split$INPAT 
amr_summary_outpat <- amr_summary_inpatoutpat_split$OUTPAT
amr_summary_matched <- merge(amr_summary_inpat, amr_summary_outpat, by = "combnew")
# correlate the two p values
cor(amr_summary_matched$p.x, amr_summary_matched$p.y)
# difference in means
mean(amr_summary_matched$p.x) - mean(amr_summary_matched$p.y)

#filter out only inpatient data
amr_summary_filtered <- amr_summary %>% filter(patientType == 'INPAT') 
#filter out combinations with less than 5 years of data, 30 observations per timepoint and less than 10 cases for N_I + N_R
amr_summary_filtered <- amr_summary_filtered %>% group_by(combR) %>% filter(n() > 5) %>% filter(all(N>=30)) %>% filter(sum(N_R + N_I) >= 10)
#add the columns N_R and N_I together and delete N_R and N_I
amr_summary_filtered <- amr_summary_filtered %>% group_by(combR) %>%  mutate(N_I_R = N_R + N_I) %>% select(-c(N_I, N_R))
#check that filtering worked properly
if(any(amr_summary_filtered$N < 30)) cat('mistake in filtering observations')
if(any(sum(amr_summary_filtered$N_I_R) < 10)) cat('mistake in filtering resistant types')
if(any(amr_summary_filtered$N_S + amr_summary_filtered$N_I_R != amr_summary_filtered$N)) cat('mistake in computing N_I_R sum')
#save the re-annotated and filtered AMR files
write.csv(x = amr_summary_filtered, file = "data/summary_AMR_filtered.csv", row.names = F)

##### AMC data ####

amc_summary <- read.csv(file = "data/original/summary_AMC_byclass.csv")
amc_summary$combC <- paste(amc_summary$class, amc_summary$Sector, amc_summary$Year, sep = "|")

# changing column names to match amr_summary convention
amc_summary$Antibiotic_class = amc_summary$class

amc_summary$class[amc_summary$class=="J01A"] <- "J01A Tetracyclines"
amc_summary$class[amc_summary$class=="J01B"] <- "J01B Amphenicols"
amc_summary$class[amc_summary$class=="J01C"] <- "J01C Penicillins"
amc_summary$class[amc_summary$class=="J01D"] <- "J01D Other Betalactams"
amc_summary$class[amc_summary$class=="J01E"] <- "J01E Sulfonamides etc."
amc_summary$class[amc_summary$class=="J01F"] <- "J01F Macrolides etc."
amc_summary$class[amc_summary$class=="J01G"] <- "J01G Aminoglycosides"
amc_summary$class[amc_summary$class=="J01M"] <- "J01M Quinolones"
amc_summary$class[amc_summary$class=="J01R"] <- "J01R Combinations"
amc_summary$class[amc_summary$class=="J01X"] <- "J01X Others"

#save the re-annotated AMC files
write.csv(x = amc_summary, file = "data/summary_AMC_byclass.csv", row.names = F)


